name: Rust

on: workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  winbuild:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Get Artifact
    - uses: actions/upload-artifact@v3
      with:
        name: chat_reader_windows
        path: target/release/chat_reader
      
  
  macbuild:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Get Artifact
    - uses: actions/upload-artifact@v3
      with:
        name: chat_reader_osx
        path: target/release/chat_reader
